//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SecurePayMessage {
    
    private MessageInfo messageInfoField;
    
    private MerchantInfo merchantInfoField;
    
    private string requestTypeField;
    
    private Payment paymentField;
    
    /// <remarks/>
    public MessageInfo MessageInfo {
        get {
            return this.messageInfoField;
        }
        set {
            this.messageInfoField = value;
        }
    }
    
    /// <remarks/>
    public MerchantInfo MerchantInfo {
        get {
            return this.merchantInfoField;
        }
        set {
            this.merchantInfoField = value;
        }
    }
    
    /// <remarks/>
    public string RequestType {
        get {
            return this.requestTypeField;
        }
        set {
            this.requestTypeField = value;
        }
    }
    
    /// <remarks/>
    public Payment Payment {
        get {
            return this.paymentField;
        }
        set {
            this.paymentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MessageInfo {
    
    private string messageIDField;
    
    private string messageTimestampField;
    
    private string timeoutValueField;
    
    private string apiVersionField;
    
    /// <remarks/>
    public string messageID {
        get {
            return this.messageIDField;
        }
        set {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    public string messageTimestamp {
        get {
            return this.messageTimestampField;
        }
        set {
            this.messageTimestampField = value;
        }
    }
    
    /// <remarks/>
    public string timeoutValue {
        get {
            return this.timeoutValueField;
        }
        set {
            this.timeoutValueField = value;
        }
    }
    
    /// <remarks/>
    public string apiVersion {
        get {
            return this.apiVersionField;
        }
        set {
            this.apiVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MerchantInfo {
    
    private string merchantIDField;
    
    private string passwordField;
    
    /// <remarks/>
    public string merchantID {
        get {
            return this.merchantIDField;
        }
        set {
            this.merchantIDField = value;
        }
    }
    
    /// <remarks/>
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Payment {
    
    private TxnList txnListField;
    
    /// <remarks/>
    public TxnList TxnList {
        get {
            return this.txnListField;
        }
        set {
            this.txnListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class TxnList {
    
    private Txn txnField;
    
    private string countField;
    
    /// <remarks/>
    public Txn Txn {
        get {
            return this.txnField;
        }
        set {
            this.txnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Txn {
    
    private string txnTypeField;
    
    private string txnSourceField;
    
    private string amountField;
    
    private string currencyField;
    
    private string purchaseOrderNoField;
    
    private CreditCardInfo creditCardInfoField;
    
    private BuyerInfo buyerInfoField;
    
    private string idField;
    
    /// <remarks/>
    public string txnType {
        get {
            return this.txnTypeField;
        }
        set {
            this.txnTypeField = value;
        }
    }
    
    /// <remarks/>
    public string txnSource {
        get {
            return this.txnSourceField;
        }
        set {
            this.txnSourceField = value;
        }
    }
    
    /// <remarks/>
    public string amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public string purchaseOrderNo {
        get {
            return this.purchaseOrderNoField;
        }
        set {
            this.purchaseOrderNoField = value;
        }
    }
    
    /// <remarks/>
    public CreditCardInfo CreditCardInfo {
        get {
            return this.creditCardInfoField;
        }
        set {
            this.creditCardInfoField = value;
        }
    }
    
    /// <remarks/>
    public BuyerInfo BuyerInfo {
        get {
            return this.buyerInfoField;
        }
        set {
            this.buyerInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CreditCardInfo {
    
    private string cardNumberField;
    
    private string cvvField;
    
    private string expiryDateField;
    
    /// <remarks/>
    public string cardNumber {
        get {
            return this.cardNumberField;
        }
        set {
            this.cardNumberField = value;
        }
    }
    
    /// <remarks/>
    public string cvv {
        get {
            return this.cvvField;
        }
        set {
            this.cvvField = value;
        }
    }
    
    /// <remarks/>
    public string expiryDate {
        get {
            return this.expiryDateField;
        }
        set {
            this.expiryDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class BuyerInfo {
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string zipCodeField;
    
    private string townField;
    
    private string billingCountryField;
    
    private string deliveryCountryField;
    
    private string emailAddressField;
    
    private string ipField;
    
    /// <remarks/>
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string zipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string town {
        get {
            return this.townField;
        }
        set {
            this.townField = value;
        }
    }
    
    /// <remarks/>
    public string billingCountry {
        get {
            return this.billingCountryField;
        }
        set {
            this.billingCountryField = value;
        }
    }
    
    /// <remarks/>
    public string deliveryCountry {
        get {
            return this.deliveryCountryField;
        }
        set {
            this.deliveryCountryField = value;
        }
    }
    
    /// <remarks/>
    public string emailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ip {
        get {
            return this.ipField;
        }
        set {
            this.ipField = value;
        }
    }
}
