//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SecurePayMessage {
    
    private MessageInfo messageInfoField;
    
    private MerchantInfo merchantInfoField;
    
    private string requestTypeField;
    
    private Status statusField;
    
    private Payment paymentField;
    
    /// <remarks/>
    public MessageInfo MessageInfo {
        get {
            return this.messageInfoField;
        }
        set {
            this.messageInfoField = value;
        }
    }
    
    /// <remarks/>
    public MerchantInfo MerchantInfo {
        get {
            return this.merchantInfoField;
        }
        set {
            this.merchantInfoField = value;
        }
    }
    
    /// <remarks/>
    public string RequestType {
        get {
            return this.requestTypeField;
        }
        set {
            this.requestTypeField = value;
        }
    }
    
    /// <remarks/>
    public Status Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public Payment Payment {
        get {
            return this.paymentField;
        }
        set {
            this.paymentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MessageInfo {
    
    private string messageIDField;
    
    private string messageTimestampField;
    
    private string apiVersionField;
    
    /// <remarks/>
    public string messageID {
        get {
            return this.messageIDField;
        }
        set {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    public string messageTimestamp {
        get {
            return this.messageTimestampField;
        }
        set {
            this.messageTimestampField = value;
        }
    }
    
    /// <remarks/>
    public string apiVersion {
        get {
            return this.apiVersionField;
        }
        set {
            this.apiVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MerchantInfo {
    
    private string merchantIDField;
    
    /// <remarks/>
    public string merchantID {
        get {
            return this.merchantIDField;
        }
        set {
            this.merchantIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Status {
    
    private string statusCodeField;
    
    private string statusDescriptionField;
    
    /// <remarks/>
    public string statusCode {
        get {
            return this.statusCodeField;
        }
        set {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    public string statusDescription {
        get {
            return this.statusDescriptionField;
        }
        set {
            this.statusDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Payment {
    
    private TxnList txnListField;
    
    /// <remarks/>
    public TxnList TxnList {
        get {
            return this.txnListField;
        }
        set {
            this.txnListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class TxnList {
    
    private Txn[] txnField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Txn")]
    public Txn[] Txn {
        get {
            return this.txnField;
        }
        set {
            this.txnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Txn {
    
    private string txnTypeField;
    
    private string txnSourceField;
    
    private string amountField;
    
    private string currencyField;
    
    private string purchaseOrderNoField;
    
    private string approvedField;
    
    private string responseCodeField;
    
    private string responseTextField;
    
    private string settlementDateField;
    
    private string txnIDField;
    
    private CreditCardInfo creditCardInfoField;
    
    private string antiFraudResponseCodeField;
    
    private string antiFraudResponseTextField;
    
    private FraudGuard fraudGuardField;
    
    private ThirdPartyResponse thirdPartyResponseField;
    
    private string idField;
    
    /// <remarks/>
    public string txnType {
        get {
            return this.txnTypeField;
        }
        set {
            this.txnTypeField = value;
        }
    }
    
    /// <remarks/>
    public string txnSource {
        get {
            return this.txnSourceField;
        }
        set {
            this.txnSourceField = value;
        }
    }
    
    /// <remarks/>
    public string amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public string purchaseOrderNo {
        get {
            return this.purchaseOrderNoField;
        }
        set {
            this.purchaseOrderNoField = value;
        }
    }
    
    /// <remarks/>
    public string approved {
        get {
            return this.approvedField;
        }
        set {
            this.approvedField = value;
        }
    }
    
    /// <remarks/>
    public string responseCode {
        get {
            return this.responseCodeField;
        }
        set {
            this.responseCodeField = value;
        }
    }
    
    /// <remarks/>
    public string responseText {
        get {
            return this.responseTextField;
        }
        set {
            this.responseTextField = value;
        }
    }
    
    /// <remarks/>
    public string settlementDate {
        get {
            return this.settlementDateField;
        }
        set {
            this.settlementDateField = value;
        }
    }
    
    /// <remarks/>
    public string txnID {
        get {
            return this.txnIDField;
        }
        set {
            this.txnIDField = value;
        }
    }
    
    /// <remarks/>
    public CreditCardInfo CreditCardInfo {
        get {
            return this.creditCardInfoField;
        }
        set {
            this.creditCardInfoField = value;
        }
    }
    
    /// <remarks/>
    public string antiFraudResponseCode {
        get {
            return this.antiFraudResponseCodeField;
        }
        set {
            this.antiFraudResponseCodeField = value;
        }
    }
    
    /// <remarks/>
    public string antiFraudResponseText {
        get {
            return this.antiFraudResponseTextField;
        }
        set {
            this.antiFraudResponseTextField = value;
        }
    }
    
    /// <remarks/>
    public FraudGuard FraudGuard {
        get {
            return this.fraudGuardField;
        }
        set {
            this.fraudGuardField = value;
        }
    }
    
    /// <remarks/>
    public ThirdPartyResponse ThirdPartyResponse {
        get {
            return this.thirdPartyResponseField;
        }
        set {
            this.thirdPartyResponseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CreditCardInfo {
    
    private string panField;
    
    private string expiryDateField;
    
    private string cardTypeField;
    
    private string cardDescriptionField;
    
    /// <remarks/>
    public string pan {
        get {
            return this.panField;
        }
        set {
            this.panField = value;
        }
    }
    
    /// <remarks/>
    public string expiryDate {
        get {
            return this.expiryDateField;
        }
        set {
            this.expiryDateField = value;
        }
    }
    
    /// <remarks/>
    public string cardType {
        get {
            return this.cardTypeField;
        }
        set {
            this.cardTypeField = value;
        }
    }
    
    /// <remarks/>
    public string cardDescription {
        get {
            return this.cardDescriptionField;
        }
        set {
            this.cardDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class FraudGuard {
    
    private string scoreField;
    
    private string infoIpCountryField;
    
    private string infoCardCountryField;
    
    private string ipCountryFailField;
    
    private string minAmountFailField;
    
    private string maxAmountFailField;
    
    private string openProxyFailField;
    
    private string ipCountryCardCountryFailField;
    
    private string ipCardFailField;
    
    private string ipRiskCountryFailField;
    
    private string ipBillingFailField;
    
    private string ipDeliveryFailField;
    
    private string billingDeliveryFailField;
    
    private string freeEmailFailField;
    
    private string tooManySameBankField;
    
    private string tooManyDeclinedField;
    
    private string tooManySameIpField;
    
    private string tooManySameCardField;
    
    private string lowHighAmountField;
    
    private tooManySameEmail tooManySameEmailField;
    
    /// <remarks/>
    public string score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    public string infoIpCountry {
        get {
            return this.infoIpCountryField;
        }
        set {
            this.infoIpCountryField = value;
        }
    }
    
    /// <remarks/>
    public string infoCardCountry {
        get {
            return this.infoCardCountryField;
        }
        set {
            this.infoCardCountryField = value;
        }
    }
    
    /// <remarks/>
    public string ipCountryFail {
        get {
            return this.ipCountryFailField;
        }
        set {
            this.ipCountryFailField = value;
        }
    }
    
    /// <remarks/>
    public string minAmountFail {
        get {
            return this.minAmountFailField;
        }
        set {
            this.minAmountFailField = value;
        }
    }
    
    /// <remarks/>
    public string maxAmountFail {
        get {
            return this.maxAmountFailField;
        }
        set {
            this.maxAmountFailField = value;
        }
    }
    
    /// <remarks/>
    public string openProxyFail {
        get {
            return this.openProxyFailField;
        }
        set {
            this.openProxyFailField = value;
        }
    }
    
    /// <remarks/>
    public string IpCountryCardCountryFail {
        get {
            return this.ipCountryCardCountryFailField;
        }
        set {
            this.ipCountryCardCountryFailField = value;
        }
    }
    
    /// <remarks/>
    public string ipCardFail {
        get {
            return this.ipCardFailField;
        }
        set {
            this.ipCardFailField = value;
        }
    }
    
    /// <remarks/>
    public string ipRiskCountryFail {
        get {
            return this.ipRiskCountryFailField;
        }
        set {
            this.ipRiskCountryFailField = value;
        }
    }
    
    /// <remarks/>
    public string ipBillingFail {
        get {
            return this.ipBillingFailField;
        }
        set {
            this.ipBillingFailField = value;
        }
    }
    
    /// <remarks/>
    public string ipDeliveryFail {
        get {
            return this.ipDeliveryFailField;
        }
        set {
            this.ipDeliveryFailField = value;
        }
    }
    
    /// <remarks/>
    public string billingDeliveryFail {
        get {
            return this.billingDeliveryFailField;
        }
        set {
            this.billingDeliveryFailField = value;
        }
    }
    
    /// <remarks/>
    public string freeEmailFail {
        get {
            return this.freeEmailFailField;
        }
        set {
            this.freeEmailFailField = value;
        }
    }
    
    /// <remarks/>
    public string tooManySameBank {
        get {
            return this.tooManySameBankField;
        }
        set {
            this.tooManySameBankField = value;
        }
    }
    
    /// <remarks/>
    public string tooManyDeclined {
        get {
            return this.tooManyDeclinedField;
        }
        set {
            this.tooManyDeclinedField = value;
        }
    }
    
    /// <remarks/>
    public string tooManySameIp {
        get {
            return this.tooManySameIpField;
        }
        set {
            this.tooManySameIpField = value;
        }
    }
    
    /// <remarks/>
    public string tooManySameCard {
        get {
            return this.tooManySameCardField;
        }
        set {
            this.tooManySameCardField = value;
        }
    }
    
    /// <remarks/>
    public string lowHighAmount {
        get {
            return this.lowHighAmountField;
        }
        set {
            this.lowHighAmountField = value;
        }
    }
    
    /// <remarks/>
    public tooManySameEmail tooManySameEmail {
        get {
            return this.tooManySameEmailField;
        }
        set {
            this.tooManySameEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class tooManySameEmail {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ThirdPartyResponse {
    
    private string returnCodeField;
    
    private string result1Field;
    
    private string result2Field;
    
    private string additionalInfo1Field;
    
    private string additionalInfo2Field;
    
    private string pSPResultField;
    
    private string pSPScoreField;
    
    private string merchantResultField;
    
    private string merchantScoreField;
    
    private string proxyIpField;
    
    private string freeEMailDomainField;
    
    private string iPCountryField;
    
    private string bINCountryField;
    
    private string geoRegionMatchField;
    
    private string geoCountryMatchField;
    
    /// <remarks/>
    public string returnCode {
        get {
            return this.returnCodeField;
        }
        set {
            this.returnCodeField = value;
        }
    }
    
    /// <remarks/>
    public string result1 {
        get {
            return this.result1Field;
        }
        set {
            this.result1Field = value;
        }
    }
    
    /// <remarks/>
    public string result2 {
        get {
            return this.result2Field;
        }
        set {
            this.result2Field = value;
        }
    }
    
    /// <remarks/>
    public string additionalInfo1 {
        get {
            return this.additionalInfo1Field;
        }
        set {
            this.additionalInfo1Field = value;
        }
    }
    
    /// <remarks/>
    public string additionalInfo2 {
        get {
            return this.additionalInfo2Field;
        }
        set {
            this.additionalInfo2Field = value;
        }
    }
    
    /// <remarks/>
    public string PSPResult {
        get {
            return this.pSPResultField;
        }
        set {
            this.pSPResultField = value;
        }
    }
    
    /// <remarks/>
    public string PSPScore {
        get {
            return this.pSPScoreField;
        }
        set {
            this.pSPScoreField = value;
        }
    }
    
    /// <remarks/>
    public string MerchantResult {
        get {
            return this.merchantResultField;
        }
        set {
            this.merchantResultField = value;
        }
    }
    
    /// <remarks/>
    public string MerchantScore {
        get {
            return this.merchantScoreField;
        }
        set {
            this.merchantScoreField = value;
        }
    }
    
    /// <remarks/>
    public string ProxyIp {
        get {
            return this.proxyIpField;
        }
        set {
            this.proxyIpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FreeE-MailDomain")]
    public string FreeEMailDomain {
        get {
            return this.freeEMailDomainField;
        }
        set {
            this.freeEMailDomainField = value;
        }
    }
    
    /// <remarks/>
    public string IPCountry {
        get {
            return this.iPCountryField;
        }
        set {
            this.iPCountryField = value;
        }
    }
    
    /// <remarks/>
    public string BINCountry {
        get {
            return this.bINCountryField;
        }
        set {
            this.bINCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Geo-RegionMatch")]
    public string GeoRegionMatch {
        get {
            return this.geoRegionMatchField;
        }
        set {
            this.geoRegionMatchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Geo-CountryMatch")]
    public string GeoCountryMatch {
        get {
            return this.geoCountryMatchField;
        }
        set {
            this.geoCountryMatchField = value;
        }
    }
}
